# Generated by Django 4.2 on 2023-04-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='Model',
        ),
    ]
