# Generated by Django 4.2 on 2023-04-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_map_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.model')),
            ],
        ),
        migrations.CreateModel(
            name='QualElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuantElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuantElementPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quantelement')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.layout')),
            ],
            options={
                'unique_together': {('element', 'layout')},
            },
        ),
        migrations.CreateModel(
            name='QualElementPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.qualelement')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.layout')),
            ],
            options={
                'unique_together': {('element', 'layout')},
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_connections', to='api.qualelement')),
                ('to_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_connections', to='api.qualelement')),
            ],
            options={
                'unique_together': {('from_element', 'to_element')},
            },
        ),
    ]
