# Generated by Django 4.2 on 2023-04-20 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_layout_qualelement_quantelement_quantelementposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='default_layout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_default', to='api.layout'),
        ),
    ]
