# Generated by Django 4.2 on 2023-04-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_model_default_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.model'),
        ),
    ]
