# Generated by Django 4.2 on 2023-04-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_layout_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.model'),
            preserve_default=False,
        ),
    ]
